theme = "coder" # set the theme
baseURL = "https://darrenwee.github.io/"

[params] # theme parameters
    author = "Darren Wee" # author's name
    info = "CS Undergrad at NUS" # author's job title or info
    description = "Darren's personal website" # site description
    keywords = "blog,developer,personal" # site keywords
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/darrenwee"
[[params.social]]
    name = "GPG_Key"
    weight = 2
    url = "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x759BF1C71690EC08"

# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
[[menu.main]]
    name = "Resume"
    weight = 2
    url = "/resume/"
[[menu.main]]
    name = "Personal"
    weight = 3
    url  = "/personal/"
